### ISSUE TITLE
Plugin broken - no module named ui.ui_settings

### ISSUE THREAD

**Issue by SteveLowman** [3nids/intersectit#13]
The plugin will not load. There is the following Python error message:
2017-09-07T17:29:25	1	Traceback (most recent call last):
			  File "C:/PROGRA\~1/QGIS2\~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/slowman/.qgis2/python/plugins\intersectit\__init__.py", line 32, in classFactory
			    from intersectit_plugin import IntersectIt
			  File "C:/PROGRA\~1/QGIS2\~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/slowman/.qgis2/python/plugins\intersectit\intersectit_plugin.py", line 37, in <module>
			    from gui.my_settings_dialog import MySettingsDialog
			  File "C:/PROGRA\~1/QGIS2\~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/slowman/.qgis2/python/plugins\intersectit\gui\my_settings_dialog.py", line 37, in <module>
			    from ..ui.ui_settings import Ui_Settings
			  File "C:/PROGRA\~1/QGIS2\~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named ui.ui_settings

This is in QGIS 2.14.17

**Comment by ponceta** [comment]
Same on QGIS 2.18.12
Comes from a bad initialization of qgissettingmanager?

**Comment by basilrabi** [comment]
Can confirm this issue (QGIS 2.18.10 on Fedora 26).

**Comment by tveinot** [comment]
Can also confirm
2017-09-22T16:46:57	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/tveinot/.qgis2/python/plugins\intersectit\__init__.py", line 32, in classFactory
			    from intersectit_plugin import IntersectIt
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/tveinot/.qgis2/python/plugins\intersectit\intersectit_plugin.py", line 37, in <module>
			    from gui.my_settings_dialog import MySettingsDialog
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/tveinot/.qgis2/python/plugins\intersectit\gui\my_settings_dialog.py", line 37, in <module>
			    from ..ui.ui_settings import Ui_Settings
			  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named ui.ui_settings

**Comment by 3nids** [comment]
should be fixed in 3.5.6
sorry for the delay

**Comment by ponceta** [comment]
I can confirm this, thanks @3nids !
